import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { testHarness } from "./helpers.js";
import { access, insert } from "../services/api/src/knowledge/store.js";
import { template } from "@formation-zero/knowledge/templates";

test("knowledge runtime grants allow version writes and locks but deny history mutation and DDL", async () => {
  const h = await testHarness();
  const role = "kb_runtime_" + randomUUID().replaceAll("-", "");
  const user = await h.register(
    "runtime@example.invalid",
    "Synthetic-Runtime-Password-91!",
  );
  const actor = { userId: user, requestId: randomUUID() };
  await h.pool.query(
    "INSERT INTO kb_grants(user_id,permission,granted_by) VALUES($1,'CONTENT_EDITOR',$1)",
    [user],
  );
  const c = await h.pool.connect();
  try {
    await c.query("BEGIN");
    // Identifiers derive only from random UUIDs generated by this test.
    await c.query(`CREATE ROLE ${role} NOLOGIN`);
    const grants = (await readFile("database/runtime-grants.sql", "utf8"))
      .replaceAll("fz_runtime", role)
      .replaceAll("SCHEMA public", "SCHEMA " + h.schema);
    await c.query(grants);
    await c.query(`SET LOCAL ROLE ${role}`);
    await access(c, actor, "CONTENT_EDITOR");
    const first = await insert(c, actor, "EQUIPMENT", template("EQUIPMENT"));
    await c.query("SELECT id FROM kb_entities WHERE id=$1 FOR UPDATE", [
      first.entity_id,
    ]);
    const next = await insert(
      c,
      actor,
      "EQUIPMENT",
      { ...first.payload, notes: "Synthetic next version" },
      first,
    );
    assert.equal(next.version, 2);
    for (const sql of [
      "UPDATE kb_entities SET id=id",
      "DELETE FROM kb_versions",
      "UPDATE kb_reviews SET comments='tampered'",
      "TRUNCATE kb_states",
      "DELETE FROM rule_evaluations",
      "UPDATE rule_activations SET reason='tampered'",
      "TRUNCATE rule_evaluations",
      "CREATE TABLE forbidden_runtime_table(id int)",
    ]) {
      await c.query("SAVEPOINT denied_action");
      await assert.rejects(c.query(sql), /immutable|permission denied/);
      await c.query("ROLLBACK TO SAVEPOINT denied_action");
    }
  } finally {
    // Rolls back the test-only role, grants and fixture changes together.
    await c.query("ROLLBACK");
    c.release();
    await h.close();
  }
});
