// Provisional values derived from visual direction, not AI-rendered hex labels.
export const tokens = {
  color: {
    backgroundPrimary: "#0c0d0e",
    backgroundSecondary: "#151719",
    surfacePrimary: "#1b1d1f",
    surfaceElevated: "#292c2f",
    textPrimary: "#f3efe7",
    textSecondary: "#c7c5bf",
    textMuted: "#aaa9a4",
    brandAccent: "#bc2438",
    brandAccentHover: "#a51e31",
    brandAccentActive: "#8f1829",
    brandText: "#ff7582",
    onAccent: "#ffffff",
    borderDefault: "#727579",
    borderStrong: "#b6b8ba",
    stateSuccess: "#a7d4b0",
    stateWarning: "#e8c483",
    stateDanger: "#ff9ca6",
    stateInfo: "#c9cdd1",
    focus: "#f0d2a0",
    sand: "#d0bd9b",
  },
  typography: {
    headingFamily: 'Impact, "Arial Narrow", system-ui, sans-serif',
    bodyFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
    dataFamily: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
    sizeSmall: 14,
    sizeBody: 17,
    sizeTitle: 32,
    sizeHero: 56,
    lineBody: 1.6,
    lineHeading: 1.1,
    tracking: 2,
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48, section: 64 },
  radius: { small: 4, medium: 8 },
  border: { thin: 1, focus: 3 },
  shadow: { none: "none", raised: "0 4px 16px #00000026" },
  motion: { fast: 120, standard: 180, reduced: 0 },
  breakpoint: { compact: 480, medium: 768, wide: 1120 },
  zIndex: { base: 0, navigation: 10, overlay: 100 },
  icon: { small: 16, medium: 24, large: 32 },
  layout: { content: 1120, reading: 720, form: 480, target: 48 },
} as const;
export const brand = {
  name: "FORMATION ZERO",
  tagline: "Readiness Starts Here.",
  board: "assets/brand/formation-zero-board.png",
  masterStatus: "AWAITING_APPROVED_VECTOR",
} as const;
