import { DEMANDS, FORMATIONS, type Kind } from "./index";
// Form starters are explicitly synthetic metadata, never fitness instructions.
const base = {
  name: "Synthetic fixture — not training guidance",
  notes: "SYNTHETIC: architecture validation only.",
};
const authoring = {
  author: "",
  rights: "",
  provenance: "FZ_ORIGINAL",
  citations: [],
  effective_date: null,
};
export function template(kind: Kind): Record<string, unknown> {
  const values: Record<Kind, Record<string, unknown>> = {
    RULE: {
      ...authoring,
      synthetic: true,
      reason_code: "",
      definition: {
        priority: 0,
        type: "HARD_BLOCK",
        condition: { op: "EQ", path: "safety.pain", value: true },
        effects: [{ type: "BLOCK_CANDIDATE" }],
        effective_from: "2026-09-05",
        effective_until: null,
        population: null,
        unknown_behavior: "BLOCK",
      },
    },
    REASON_CODE: {
      ...authoring,
      synthetic: true,
      reason: {
        category: "SAFETY",
        explanation: "Synthetic constraint; not training guidance.",
        severity: "BLOCK",
      },
    },
    PRESCRIPTION_TEMPLATE: {
      ...authoring,
      synthetic: true,
      definition: {
        objective: "CUSTOM",
        slots: [],
        buffer_seconds: 0,
        limit_units: {},
      },
    },
    RULE_SET: { ...authoring, synthetic: true, rules: [] },
    SOURCE: {
      issuing_authority: "Synthetic authority",
      source_type: "OTHER",
      source_url: "",
      publication_number: "SYNTHETIC",
      publication_date: null,
      provenance: "FZ_ORIGINAL",
    },
    SOURCE_VERSION: {
      source: "",
      version_identifier: "synthetic-v1",
      effective_date: null,
      superseded_date: null,
      change_identifier: "",
      checksum: "",
      locator: "synthetic://source/v1",
    },
    SOURCE_SECTION: {
      source_version: "",
      section_code: "SYN-1",
      page_start: 1,
      page_end: 1,
      paragraph_locator: "synthetic paragraph",
      excerpt_note: "No copied source text.",
      normalized_locator: "synthetic://source/v1/section/1",
    },
    CITATION: {
      section: "",
      purpose: "Synthetic linkage validation",
      support_type: "Synthetic support",
    },
    AUTHOR: {
      author_role: "Synthetic author",
      public_affiliation: "",
      platform_user_id: null,
      active: true,
    },
    QUALIFICATION: {
      person: "",
      credential_name: "Synthetic credential",
      issuing_organization: "Synthetic issuer",
      credential_identifier: "",
      issued_date: null,
      expiration_date: null,
      status: "INACTIVE",
    },
    REVIEWER: {
      person: "",
      user_id: "",
      review_types: ["TECHNICAL"],
      specialties: [],
      active: true,
    },
    EQUIPMENT: {
      aliases: [],
      category: "Synthetic equipment",
      mobility: "NONE",
      quantity_semantics: "NONE",
      provenance: "FZ_ORIGINAL",
    },
    RESTRICTION: {
      category: "Synthetic category",
      body_region: "Unspecified",
      severity: "Synthetic only",
      eligibility_behavior: "Metadata only; no automated restriction",
      source: "",
      reviewer: "",
    },
    EXERCISE: {
      ...authoring,
      aliases: [],
      equipment: [],
      summary: "Synthetic schema fixture, not an exercise prescription.",
      instructions: "No training instruction. Synthetic test data only.",
      primary_movement: "Brace",
      secondary_movements: [],
      primary_capability: "Stability",
      secondary_capabilities: [],
      technical_complexity: 1,
      demand_profile: Object.fromEntries(DEMANDS.map((k) => [k, 0])),
      formation_suitability: Object.fromEntries(FORMATIONS.map((k) => [k, 0])),
      individual_suitability: 0,
      scaling_available: false,
      restrictions: [],
      media_requirement: "",
      media_assets: [],
      parent_exercise: null,
      variant: null,
      relationships: [],
    },
    RECOVERY: {
      ...authoring,
      aliases: [],
      equipment: [],
      category: "Synthetic",
      purpose: "Schema validation only",
      typical_use: "Not guidance",
      demand: 0,
      intensity: "Synthetic",
      duration_guidance: "No recommended duration",
      body_area: "Unspecified",
      relationships: [],
    },
    MEDIA_REQUIREMENT: {
      media_requirement_type: "STILL_SEQUENCE",
      minimum_images: 1,
      recommended_images: 3,
      maximum_images: 4,
      required_views: ["START", "KEY_POSITION", "FINISH"],
      motion_complexity: "LOW",
      video_recommended: false,
      video_required: false,
      technical_media_review_required: true,
      rights_review_required: true,
    },
    MEDIA_ASSET: {
      ...authoring,
      asset_type: "IMAGE",
      view: "START",
      storage_locator: "synthetic://no-file",
      checksum: "synthetic-not-a-real-media-file",
      width: 1,
      height: 1,
      duration_seconds: null,
      creator: "Synthetic creator",
    },
    RIGHTS: {
      classification: "UNKNOWN",
      rights_holder: "Synthetic holder",
      creator: "Synthetic creator",
      source: "",
      license: "",
      commercial_use_allowed: false,
      modification_allowed: false,
      attribution_required: false,
      permission_reference: "",
    },
  };
  return { ...base, ...values[kind] };
}
